# Generated by Django 4.1.5 on 2023-01-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='defaut.jpg', upload_to='post_images/', verbose_name='Project photo')),
                ('title', models.CharField(help_text='maximum 50 characters', max_length=50, verbose_name='Project name')),
                ('description', models.CharField(blank=True, help_text='maximum 255 characters', max_length=255, null=True, verbose_name='Description')),
                ('url', models.URLField(blank=True, help_text='Project url or link', max_length=255, null=True, verbose_name='Link to project')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
